### PR TITLE
Fix for issue 252 (amends PR 247)

### LINKED ISSUE #252: [WalletKit]
**SDK Affected**

WalletKit 1.3.2

**Describe the bug**

```log
io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value
       at WebSocketHandler.connect.<fn>(websocket_handler.dart:70)
       at _StreamSinkWrapper.close(dart:async)
       at _HandlerSink.close(handler_transformer.dart:88)
       at _StreamSinkWrapper.close(dart:async)
       at _CloseGuaranteeSink.close(close_guarantee_channel.dart:81)
       at _StreamSinkWrapper.close(dart:async)
       at _CloseGuaranteeSink.close(close_guarantee_channel.dart:81)
       at Client.close(client.dart:136)
       at Peer.close(peer.dart:220)
       at Peer.listen.<fn>(peer.dart:208)
```

**To Reproduce**

We are unsure of the reproduction steps, as we collected this information from our Crashlytics.

### PR DESCRIPTION
**Pull request by quetool**
# Description

Resolves https://github.com/reown-com/reown_flutter/issues/252
Amends https://github.com/reown-com/reown_flutter/pull/247

## Due Dilligence

* [ ] Breaking change
* [ ] Requires a documentation update

### CODE REVIEW

File: packages/reown_core/lib/relay_client/websocket/websocket_handler.dart [hunk 1]
```diff
@@ -53,26 +56,26 @@ class WebSocketHandler implements IWebSocketHandler {
...
+      onError: (error) => _inputController!.addError(error),
+      onDone: () => _inputController!.close(),
         );
 
     // Route outgoing messages through the output controller
-    outputController.stream.listen(
+    _outputController!.stream.listen(
       (data) => _socket!.sink.add(data),
       onError: (error) => _socket!.sink.addError(error),
       onDone: () => _socket!.sink.close(),
```
Comment (AlexV525) [inline packages/reown_core/lib/relay_client/websocket/websocket_handler.dart:73]: These are still potential issues. You can obtain the socket as a local variable to avoid the outer reference plus the forced nullability conversion.

See: https://github.com/AstroxNetwork/reown_flutter/commit/3a05039528425fec9ac41305e8dd0db20c8a4059

**Review by AlexV525 — CHANGES_REQUESTED** [review]

File: packages/reown_core/lib/relay_client/websocket/websocket_handler.dart (hunk 1 above)
Comment (quetool) [reply packages/reown_core/lib/relay_client/websocket/websocket_handler.dart]: I have applied null-safety so we are all happy. Local _socket variable would require a much broader refactor as closeReason and closeCode are used elsewhere.

File: packages/reown_core/lib/relay_client/websocket/websocket_handler.dart [hunk 2]
```diff
@@ -21,8 +21,11 @@ class WebSocketHandler implements IWebSocketHandler {
   @override
   StreamChannel<String>? get channel => _channel;
 
+  StreamController<String>? _inputController;
+  StreamController<String>? _outputController;
+
   @override
-  Future<void> get ready => _socket!.ready;
+  Future<void> get ready => _socket?.ready ?? Future.value();
```
Comment (AlexV525) [inline packages/reown_core/lib/relay_client/websocket/websocket_handler.dart:28]: It seems the fallback value breaks the semantic. If the socket does not exists the value means *ready*. But I'm not sure if we can have a better solution here.

Comment (quetool) [reply packages/reown_core/lib/relay_client/websocket/websocket_handler.dart:28]: Correct. ready is not actually used anywhere AFAIK so at least this one I can remove. I'll check better later.

**Comment by agarwalrahul2702** [comment]
hey @quetool by when we can except an update on this? when u are planning to release
